### ISSUE TITLE
Undefined symbol error

### ISSUE THREAD

**Issue by oierlauzi** [I2PC/xmippViz#64]
libXmippJNI.so: /home/carlos/scipion3/xmipp-bundle/build/lib/libXmippJNI.so: undefined symbol: _ZN13MultidimArrayIN10half_float4halfEE6resizeEmmmmb
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:872)
	at java.lang.System.loadLibrary(System.java:1124)
	at xmipp.jni.MetaData.<clinit>(MetaData.java:98)
	at xmipp.viewer.scipion.ScipionViewer.openFile(ScipionViewer.java:69)
	at xmipp.viewer.scipion.ScipionViewer.main(ScipionViewer.java:52)

**Comment by oierlauzi** [comment]
There was an old XmippCore.so in path
